# Generated by Django 3.0.8 on 2021-01-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='description should be here!', max_length=100),
        ),
    ]
